# Generated by Django 3.1.7 on 2021-02-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blossom_app', '0002_users_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='avatar',
        ),
    ]
