# Generated by Django 3.1.7 on 2021-02-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blossom_app', '0004_chat_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='user',
        ),
        migrations.AddField(
            model_name='quotes',
            name='quote_author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='the_quote',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
