# Generated by Django 3.1.7 on 2021-02-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blossom_app', '0006_intentions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
